// Generated by CoffeeScript 1.6.2
(function() {
  var redis;

  redis = require("./redis");

  exports.get = function(id, done) {
    return redis.get("graph", id, done);
  };

}).call(this);

/*
//@ sourceMappingURL=graphsCache.map
*/
