// Generated by CoffeeScript 1.6.2
(function() {
  var client, get, redis, set;

  redis = require("redis");

  client = redis.createClient(process.env.REDIS_PORT, process.env.REDIS_HOST);

  client.auth(process.env.REDIS_PASSWORD, function(err) {
    return console.log("Redis connect : " + err);
  });

  get = function(type, key, done) {
    return client.get(type + "_" + key, function(err, reply) {
      if (!err && reply) {
        reply = JSON.parse(reply);
      }
      return done(err, reply);
    });
  };

  set = function(type, key, data) {
    return client.set(type + "_" + key, JSON.stringify(data));
  };

  exports.get = get;

  exports.set = set;

}).call(this);

/*
//@ sourceMappingURL=redis.map
*/
