// Generated by CoffeeScript 1.6.2
(function() {
  var client, del, get, getJSON, redis, set, setJSON;

  redis = require("redis");

  client = redis.createClient(process.env.REDIS_PORT, process.env.REDIS_HOST);

  client.auth(process.env.REDIS_PASSWORD, function(err) {
    return console.log("Redis connect : " + err);
  });

  get = function(type, key, done) {
    return client.get(type + "_" + key, function(err, reply) {
      return done(err, reply);
    });
  };

  set = function(type, key, data) {
    return client.set(type + "_" + key, data, redis.print);
  };

  del = function(type, key) {
    return client.del(type + "_" + key, redis.print);
  };

  getJSON = function(type, key, done) {
    return get(type, key, function(err, reply) {
      return done(err, (!err && reply ? JSON.parse(reply) : void 0));
    });
  };

  setJSON = function(type, key, data) {
    return set(type, key, JSON.stringify(data));
  };

  exports.get = get;

  exports.set = set;

  exports.del = del;

  exports.getJSON = getJSON;

  exports.setJSON = setJSON;

}).call(this);

/*
//@ sourceMappingURL=redis.map
*/
