// Generated by CoffeeScript 1.6.2
(function() {
  var cache, es, request, _del;

  request = require("./request");

  cache = require("./cache/redis");

  es = require("event-stream");

  _del = function(req) {
    var r;

    r = {
      isAuthenticated: function() {
        return req.isAuthenticated();
      },
      user: req.user,
      query: {
        ref: req.body.id
      },
      body: {},
      method: "get"
    };
    return request.req(r, null, "contrib_graphs", false, es.join(function(err, data) {
      var j;

      console.log("delete graph from cache" + err);
      if (!err) {
        j = JSON.parse(data);
        return cache.del("graph", j);
      }
    }));
  };

  exports.get = function(req, res) {
    return request.req(req, res, "contribs");
  };

  exports.post = function(req, res) {
    return request.req(req, res, "contribs");
  };

  exports.put = function(req, res) {
    return request.req(req, res, "contribs", _del(req));
  };

  exports.patch = function(req, res) {
    return request.req(req, res, "contribs", _del(req));
  };

  exports["delete"] = function(req, res) {
    return request.req(req, res, "contribs", _del(req));
  };

  exports.copy = function(req, res) {
    return request.req(req, res, "contribs");
  };

}).call(this);

/*
//@ sourceMappingURL=contribs.map
*/
