// Generated by CoffeeScript 1.6.2
(function() {
  var request;

  request = require("./request");

  exports.get = function(req, res) {
    return request.req(req, res, "contribs");
  };

  exports.post = function(req, res) {
    return request.req(req, res, "contribs");
  };

  exports.put = function(req, res) {
    return request.req(req, res, "contribs");
  };

  exports.patch = function(req, res) {
    return request.req(req, res, "contribs");
  };

  exports["delete"] = function(req, res) {
    return request.req(req, res, "contribs");
  };

}).call(this);

/*
//@ sourceMappingURL=contribs.map
*/
