// Generated by CoffeeScript 1.6.2
(function() {
  var async, cache, es, request;

  request = require("./request");

  cache = require("./cache/redis");

  async = require("async");

  es = require("event-stream");

  exports.get = function(req, res) {
    var ref;

    ref = !req.query.graph ? "_default" : req.query.graph;
    console.log(ref);
    return async.waterfall([
      function(ck) {
        if (req.query.context !== "data") {
          return cache.get("graph", ref, ck);
        } else {
          return ck(null, null);
        }
      }, function(r, ck) {
        if (!r) {
          return request.req(req, res, "graphs", true, es.join(ck));
        } else {
          console.log("graph found in cache it's allrigth!");
          res.writeHead(200, {
            'Content-Type': 'application/json'
          });
          res.write(r);
          res.end();
          return ck(null, null);
        }
      }
    ], function(err, data) {
      if (!err && data) {
        return cache.set("graph", ref, data);
      }
    });
  };

  exports.post = function(req, res) {
    return request.req(req, res, "graphs", true);
  };

  exports.put = function(req, res) {
    return request.req(req, res, "graphs", true);
  };

  exports.patch = function(req, res) {
    return request.req(req, res, "graphs", true);
  };

  exports["delete"] = function(req, res) {
    return request.req(req, res, "graphs", true);
  };

}).call(this);

/*
//@ sourceMappingURL=graphs.map
*/
