// Generated by CoffeeScript 1.6.2
(function() {
  var request;

  request = require("request");

  exports.get = function(req, res) {
    var userName;

    if (req.isAuthenticated()) {
      userName = req.user.name;
    }
    return request({
      uri: "" + process.env.DISPATCH_URL + "/users",
      qs: {
        user: userName
      }
    }).pipe(res);
  };

}).call(this);

/*
//@ sourceMappingURL=users.map
*/
